registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000

registry-pass-thru:
  restart: always
  image: registry:2
  ports:
    - 5001:5001
  volumes:
    - ./registry.yml:/etc/docker/registry/config.yml
  links:
    - registry


